baseurl = "https://indra.my.id/"
title = "Indra Gunawan"
author = "Indra Gunawan"
theme = "blackburn"
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10
languageCode = "id"

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  subtitle = "Learn and Share"
  brand = "Blackburn"
  googleAnalytics = "UA-87027704-1"
  disqus = "indragunawan-github"
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[permalinks]
  post = "/:year/:month/:slug/"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 0
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 1
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topic"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 5
    url = "/contact/"

[social]
  github = "IndraGunawan"
  twitter = "rengatkids"
  instagram = "gunawan_indra"
  linkedin = "indragun"
